apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-azop
  namespace: jvm-build-gvkp-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rh_ee_tnevrlka/test-images@sha256:6a7823984f67f6309911b816a432af9a5c849604cf28a744346c64a6e0aa555b
        name: container-image
        resources: {}
status: {}
